[tool.poetry]
name = "bedrock-tandarts-api"
version = "0.1.0"
description = ""
authors = ["Remco Kersten"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.153"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
